

-- CONSTRAINTs for Pool of just_like_others


USE just_like_others

GO 

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'AK_Pool_City')
	ALTER TABLE dbo.[Pool] DROP CONSTRAINT AK_Pool_City

GO

ALTER TABLE dbo.[Pool] ADD CONSTRAINT AK_Pool_City UNIQUE (City)

GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'AK_Pool_Name')
	ALTER TABLE dbo.[Pool] DROP CONSTRAINT AK_Pool_Name

GO

ALTER TABLE dbo.[Pool] ADD CONSTRAINT AK_Pool_Name UNIQUE ([Name])

GO

IF EXISTS(SELECT * FROM sys.sysobjects WHERE xtype = 'D' AND [NAME] = 'DF_Pool_ModifiedDate')
	ALTER TABLE dbo.[Pool] DROP CONSTRAINT DF_Pool_ModifiedDate

GO

ALTER TABLE dbo.[Pool] ADD CONSTRAINT DF_Pool_ModifiedDate DEFAULT GETDATE() FOR ModifiedDate

GO